# CMakeList.txt : CMake project for Bore, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)

project ("Bore")

# Add source to this project's executable.
add_executable (Bore "Bore/Bore.cpp" "Bore/Bore.h")

# TODO: Add tests and install targets if needed.
